# fly.toml app configuration file generated for stlilyanna on 2023-09-05T12:38:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stlilyanna"
primary_region = "jnb"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
